### ISSUE TITLE
Create story template

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/v43-tier1-team-08#16]
Create html story template with css including

- [ ] Story title
- [ ] Story text
- [ ] Areas for the entered words

**Comment by mmsaki** [comment]
Some updates:

- You are doing amazing work already! @terrifricker 
- I have configured the deployment here on GitHub so the changes point to live edits on the development branch when merged. See: https://chingu-voyages.github.io/v43-tier1-team-08/ 


- Remember to include some context behind where the content of this issue #16 and will be positioned on the webpage. Is it possible for you to center it exactly where you see it on the website design? For reference:

<img width="497" alt="Screenshot 2023-03-16 at 2 02 06 PM" src="https://user-images.githubusercontent.com/98189596/225768268-dbbfb8b4-717d-4656-b9b7-054fb705147a.png">

**Comment by terrifricker** [comment]
@AustonBoyd was going to write the html and css for the landing page.  This is just the html and css for the story that will then be put in the container waiting on the landing page.

**Comment by terrifricker** [comment]
Here is a link to the epic and user stories https://docs.google.com/document/d/1Q01CCIPV1vjF6JNIfZ3m2GWq6bVn_Qsw-mrPHtse0So/edit and shows the assignments
