### ISSUE TITLE
Create initial javascript functionality

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/v43-tier1-team-08#17]
Create javascript functionality that inserts words from the form into the story template.

**Comment by mmsaki** [comment]
Hey, @terrifricker awesome work! I see that you have created a `app.js`. Just wanted to add that the script is not present in the HTML. Usually, you would want to add a script tag like this `<script src='app.js'></script>` inside the `index.HTML`

**Comment by mmsaki** [comment]
Also, I have configured the deploy here on GitHub so the changes are live when merged. See: https://chingu-voyages.github.io/v43-tier1-team-08/ 

- I wanted to also leave some context behind the specifications for the website for reference so it fits around the work you are building on this issue. 

<img width="497" alt="Screenshot 2023-03-16 at 2 02 06 PM" src="https://user-images.githubusercontent.com/98189596/225768268-dbbfb8b4-717d-4656-b9b7-054fb705147a.png">

**Comment by terrifricker** [comment]
Yes, I will add that.  There was no index.html when I created it.
