### ISSUE TITLE
Issue: Handle multiple stories and optimize how data is read and stored

### ISSUE THREAD

**Issue by mmsaki** [chingu-voyages/v43-tier1-team-08#49]
## Acceptance Criteria

- [x] A user I must be able to experience at least five different madlib stories.

<br />
<br />

## Additional optimization 1: DRY ISSUE

- Using hard corded input variables to replace blanks on our stories could be  [DRY principles](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) problem

This issue is in reference to our current app.js
https://github.com/chingu-voyages/v43-tier1-team-08/blob/288a74d645e8f378254bc03b2b7e231ead889d46/app.js#L1-L24

- This approach can work for two stories, and even for five stories. 
- If possible, depending on how you wish to handle additional stories, the challenge here is, what are other ways could you handle additional stories without repeating this code 5 more times? Or is this good enough to go with?

## Helpful tips?

Looking for where to start to handle data dynamically? I would suggest implementing some datastructures like arrays or dictionaries to store stories, classify them, destructure, read and write to them and send that information to the DOM as needed.

1. Ex. Arrays of words

```js
const words = ["Word1", "Word2", "Word3"];
```

2. Here's an example of Javascript Objects (JSON) to strore parts of speech + categories

```js
 {
    "noun": ["food", "clothing", "a place", "a game", "animal", "room"],
    "adjective": ["a color", "-est", "-ous", "-able"],
    "verb": ["action", "passed tense", "ends in -ing"],
    "misc": ["a feeling"]
  }
```

> NOTE: I am not implying that the current approach doesn't work, rather, maybe re-name the variables to `input1` `input2` so that they can adapt any other format you give it. 

## Additional optimization 2: `innerHTML` security

https://github.com/chingu-voyages/v43-tier1-team-08/blob/288a74d645e8f378254bc03b2b7e231ead889d46/app.js#L39

- There are various ways to manipulate the DOM but worth thinking about the documented security issue with using `innerHMTL` to inject code into the HTML see [security coniderations](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations)

### Review

- The goal of this issue is to meet the acceptance criteria, and not to optimize the code
- If it's already working as expected, meeting additional optimization specs is not a requirement. 
- As long as it's working this issue will be closed.

**Comment by terrifricker** [comment]
Great issue @mmsaki !  I've optimized data reading and storage with for loops.  I was trying to use textContent for the MVP, but switched to innerHTML to get the job done quickly.  I'll read about security for textContent again.  I think I can move to using it instead, but I'd like to make a pull request for the work so far using innerHTML.

**Comment by terrifricker** [comment]
I made a working prototype at: https://codepen.io/terrifricker/pen/YzOJzrK

**Comment by terrifricker** [comment]
The pull requests that were part of this issue were:
#58 
#60 
#62
